on:
  push:
    branches:
      - 'main'

name: Create Release

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version
        run: echo "VERSION=$(git rev-list --count HEAD)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: select.bash
          tag_name: v${{ env.VERSION }}
